### ISSUE TITLE
Error while trying to run tellma locally  

### ISSUE THREAD

**Issue by mohanad1213** [tellma-ltd/tellma#2]
after forking to project and deploy all the DB project according to the instructions 
we face this error
can you please help 
![Capture](https://user-images.githubusercontent.com/10624476/118722864-bee31100-b83d-11eb-8278-bf9b23464d6c.PNG)
thank in advancece

**Comment by ahmadakra** [comment]
Sorry the readme is a bit outdated, will get it fixed.
The project [configuration file](https://github.com/tellma-ltd/tellma/blob/master/Tellma/appsettings.json) contains a flag SmsEnabled.
You can override this value like so: right click the Tellma project in visual studio -> Manage User secrets. In user secrets either:
(1) Simply set SmsEnabled to false to disable SMS support:
```
  "SmsEnabled": false

```
(2) Or supply valid details for Twilio integration if you wish to enable SMS support:
```
  "Twilio": {
    "AccountSid": "<YourAccountSid>",
    "AuthToken": "<YourAuthToken>",
    "Sms": {
      "ServiceSid": "<YourServiceSid>",
      "CallbacksEnabled": false
    }
  },

```

**Comment by ahmadakra** [comment]
README.md has been updated with the new instructions.
